# Shared MLP1 product-build flag contract for GNU make users.

UMRK_MLP1_TARGET_SOC ?= rk3566
UMRK_MLP1_TARGET_CPU ?= cortex-a55
UMRK_MLP1_TUNE_FLAGS ?= -mcpu=cortex-a55 -mtune=cortex-a55
UMRK_MLP1_COMMON_CFLAGS ?= -ffunction-sections -fdata-sections -DNDEBUG
UMRK_MLP1_COMMON_CXXFLAGS ?= -ffunction-sections -fdata-sections -DNDEBUG
UMRK_MLP1_COMMON_LDFLAGS ?= -Wl,--gc-sections

UMRK_MLP1_RELEASE_CFLAGS ?= -O2 $(UMRK_MLP1_TUNE_FLAGS) $(UMRK_MLP1_COMMON_CFLAGS)
UMRK_MLP1_RELEASE_CXXFLAGS ?= -O2 $(UMRK_MLP1_TUNE_FLAGS) $(UMRK_MLP1_COMMON_CXXFLAGS)
UMRK_MLP1_SIZE_CFLAGS ?= -Os $(UMRK_MLP1_TUNE_FLAGS) $(UMRK_MLP1_COMMON_CFLAGS)
UMRK_MLP1_SIZE_CXXFLAGS ?= -Os $(UMRK_MLP1_TUNE_FLAGS) $(UMRK_MLP1_COMMON_CXXFLAGS)
UMRK_MLP1_PERF_CFLAGS ?= -O3 $(UMRK_MLP1_TUNE_FLAGS) $(UMRK_MLP1_COMMON_CFLAGS)
UMRK_MLP1_PERF_CXXFLAGS ?= -O3 $(UMRK_MLP1_TUNE_FLAGS) $(UMRK_MLP1_COMMON_CXXFLAGS)
UMRK_MLP1_DEBUG_CFLAGS ?= -g -O0 $(UMRK_MLP1_TUNE_FLAGS) -DDEBUG
UMRK_MLP1_DEBUG_CXXFLAGS ?= -g -O0 $(UMRK_MLP1_TUNE_FLAGS) -DDEBUG
UMRK_MLP1_DEBUG_LDFLAGS ?=

MLP1_BUILD_PROFILE ?= release

ifeq ($(MLP1_BUILD_PROFILE),release)
UMRK_MLP1_PROFILE_CFLAGS ?= $(UMRK_MLP1_RELEASE_CFLAGS)
UMRK_MLP1_PROFILE_CXXFLAGS ?= $(UMRK_MLP1_RELEASE_CXXFLAGS)
UMRK_MLP1_PROFILE_LDFLAGS ?= $(UMRK_MLP1_COMMON_LDFLAGS)
else ifeq ($(MLP1_BUILD_PROFILE),size)
UMRK_MLP1_PROFILE_CFLAGS ?= $(UMRK_MLP1_SIZE_CFLAGS)
UMRK_MLP1_PROFILE_CXXFLAGS ?= $(UMRK_MLP1_SIZE_CXXFLAGS)
UMRK_MLP1_PROFILE_LDFLAGS ?= $(UMRK_MLP1_COMMON_LDFLAGS)
else ifeq ($(MLP1_BUILD_PROFILE),perf)
UMRK_MLP1_PROFILE_CFLAGS ?= $(UMRK_MLP1_PERF_CFLAGS)
UMRK_MLP1_PROFILE_CXXFLAGS ?= $(UMRK_MLP1_PERF_CXXFLAGS)
UMRK_MLP1_PROFILE_LDFLAGS ?= $(UMRK_MLP1_COMMON_LDFLAGS)
else ifeq ($(MLP1_BUILD_PROFILE),debug)
UMRK_MLP1_PROFILE_CFLAGS ?= $(UMRK_MLP1_DEBUG_CFLAGS)
UMRK_MLP1_PROFILE_CXXFLAGS ?= $(UMRK_MLP1_DEBUG_CXXFLAGS)
UMRK_MLP1_PROFILE_LDFLAGS ?= $(UMRK_MLP1_DEBUG_LDFLAGS)
else
$(error unsupported MLP1_BUILD_PROFILE: $(MLP1_BUILD_PROFILE))
endif
